export interface TutorialStep {
  id: number
  phase: string
  title: string
  content: string
  target: string
  position?: 'top' | 'bottom' | 'left' | 'right' | 'center'
  actionType?: 'click' | 'select' | 'draw' | 'type' | 'slide' | 'submit' | 'activate_layer' | 'none'
  waitForAction?: boolean
  onNext?: () => void | Promise<void>
}

export const tutorialSteps: TutorialStep[] = [
  // ─── Phase 1: Map Basics (Steps 1–5) ───────────────────────────
  {
    id: 1,
    phase: 'Map Basics',
    title: 'Choose a Base Map',
    content: 'Click on the "Base Maps" tab to see different map styles you can use as the background.',
    target: '[data-tutorial="basemaps-tab"]',
    position: 'right',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 2,
    phase: 'Map Basics',
    title: 'Apply a Base Map',
    content: 'Click on any base map thumbnail to apply it to the map. Try "OpenStreetMap" for a detailed view.',
    target: '[data-tutorial="basemap-first"]',
    position: 'bottom',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 3,
    phase: 'Map Basics',
    title: 'Explore Data Layers',
    content: 'Click on the "Data" tab to see available data layers you can overlay on the map.',
    target: '[data-tutorial="data-tab"]',
    position: 'right',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 4,
    phase: 'Map Basics',
    title: 'Activate a Layer',
    content: 'Click on any layer to activate it. The layer will appear on the map with its color scheme.',
    target: '[data-tutorial="data-tab-content"]',
    position: 'left',
    actionType: 'activate_layer',
    waitForAction: true,
  },
  {
    id: 5,
    phase: 'Map Basics',
    title: 'Understanding the Legend',
    content: 'The legend shows what each color represents in the active layer. It helps you interpret the map data.',
    target: '[data-tutorial="legend"]',
    position: 'left',
    actionType: 'none',
    waitForAction: false,
  },

  // ─── Phase 2: Country & Export (Steps 6–7) ──────────────────────
  {
    id: 6,
    phase: 'Navigation & Export',
    title: 'Select a Country',
    content: 'Use the country selector to zoom to a specific African country and see its boundaries.',
    target: '[data-tutorial="country-selector"]',
    position: 'bottom',
    actionType: 'select',
    waitForAction: true,
  },
  {
    id: 7,
    phase: 'Navigation & Export',
    title: 'Export Your Map',
    content: 'Click "Export" to save the current map view as an image for reports or presentations.',
    target: '[data-tutorial="export-button"]',
    position: 'bottom',
    actionType: 'click',
    waitForAction: true,
  },

  // ─── Phase 3: Reporting Invalid Data (Steps 8–12) ───────────────
  {
    id: 8,
    phase: 'Reporting Invalid Data',
    title: 'Start Reporting',
    content: 'Found incorrect data? Click "Report Invalid Data" to flag it for review.',
    target: '[data-tutorial="report-button"]',
    position: 'bottom',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 9,
    phase: 'Reporting Invalid Data',
    title: 'Choose a Drawing Tool',
    content: 'Select either the rectangle or polygon tool from the draw control to outline the incorrect area.',
    target: '[data-tutorial="draw-control"]',
    position: 'bottom',
    actionType: 'select',
    waitForAction: true,
  },
  {
    id: 10,
    phase: 'Reporting Invalid Data',
    title: 'Draw the Area',
    content: 'Draw a shape around the area with incorrect data. Be as precise as possible.',
    target: '[data-tutorial="map-container"]',
    position: 'center',
    actionType: 'draw',
    waitForAction: true,
  },
  {
    id: 11,
    phase: 'Reporting Invalid Data',
    title: 'Add a Comment & Submit',
    content: 'Describe what\'s wrong with the data, then click "Submit" to send your report for review.',
    target: '[data-tutorial="report-submit"]',
    position: 'top',
    actionType: 'submit',
    waitForAction: true,
  },

  // ─── Phase 4: Compare Layers (Steps 13–22) ──────────────────────
  {
    id: 13,
    phase: 'Compare Layers',
    title: 'Start Compare Mode',
    content: 'Click "Compare Layers" to view two different layers side by side and see changes over time.',
    target: '[data-tutorial="compare-button"]',
    position: 'bottom',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 14,
    phase: 'Compare Layers',
    title: 'Select Left Layer Group',
    content: 'Choose a group for the left side of the comparison. This will be your "before" or reference layer.',
    target: '[data-tutorial="compare-left-group"]',
    position: 'right',
    actionType: 'select',
    waitForAction: true,
  },
  {
    id: 15,
    phase: 'Compare Layers',
    title: 'Select Left Layer',
    content: 'Now select the specific layer to display on the left side.',
    target: '[data-tutorial="compare-left-layer"]',
    position: 'right',
    actionType: 'select',
    waitForAction: true,
  },
  {
    id: 16,
    phase: 'Compare Layers',
    title: 'Select Right Layer Group',
    content: 'Choose a group for the right side. This will be your "after" or comparison layer.',
    target: '[data-tutorial="compare-right-group"]',
    position: 'left',
    actionType: 'select',
    waitForAction: true,
  },
  {
    id: 17,
    phase: 'Compare Layers',
    title: 'Select Right Layer',
    content: 'Select the specific layer for the right side of the comparison.',
    target: '[data-tutorial="compare-right-layer"]',
    position: 'left',
    actionType: 'select',
    waitForAction: true,
  },
  {
    id: 18,
    phase: 'Compare Layers',
    title: 'Enter Compare Mode',
    content: 'Click "Compare" to enter the side-by-side comparison view.',
    target: '[data-tutorial="compare-modal-submit"]',
    position: 'top',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 19,
    phase: 'Compare Layers',
    title: 'Use the Slider',
    content: 'Drag the slider left or right to reveal more of one layer or the other. Compare the differences!',
    target: '[data-tutorial="compare-slider"]',
    position: 'center',
    actionType: 'slide',
    waitForAction: true,
  },
  {
    id: 20,
    phase: 'Compare Layers',
    title: 'Edit Left Layer',
    content: 'Click on the left layer label to change it and try a different comparison.',
    target: '[data-tutorial="compare-left-label"]',
    position: 'bottom',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 21,
    phase: 'Compare Layers',
    title: 'Choose New Layer & Confirm',
    content: 'Select a different layer from the dropdown and click "Confirm" to update the comparison.',
    target: '[data-tutorial="edit-modal-confirm"]',
    position: 'top',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 22,
    phase: 'Compare Layers',
    title: 'Exit Compare Mode',
    content: 'Click "Exit" to return to the normal map view.',
    target: '[data-tutorial="compare-exit"]',
    position: 'top',
    actionType: 'click',
    waitForAction: true,
  },

  // ─── Phase 5: Statistical Analysis (Steps 23–29) ────────────────
  {
    id: 23,
    phase: 'Statistical Analysis',
    title: 'Access Statistics',
    content: 'Click on the "Stats" tab to calculate land cover statistics for any area you draw.',
    target: '[data-tutorial="stats-tab"]',
    position: 'right',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 24,
    phase: 'Statistical Analysis',
    title: 'Select a Layer for Stats',
    content: 'Choose a layer that has statistics capability. Look for layers marked with stats support.',
    target: '[data-tutorial="stats-layer-select"]',
    position: 'bottom',
    actionType: 'select',
    waitForAction: true,
  },
  {
    id: 25,
    phase: 'Statistical Analysis',
    title: 'Start Drawing for Stats',
    content: 'Click "Start Drawing" to begin. You\'ll draw an area to calculate its land cover composition.',
    target: '[data-tutorial="stats-start-drawing"]',
    position: 'bottom',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 26,
    phase: 'Statistical Analysis',
    title: 'Select Drawing Tool',
    content: 'Choose rectangle or polygon tool to draw your analysis area.',
    target: '[data-tutorial="draw-control"]',
    position: 'bottom',
    actionType: 'select',
    waitForAction: true,
  },
  {
    id: 27,
    phase: 'Statistical Analysis',
    title: 'Draw Analysis Area',
    content: 'Draw a small area on the map. Note: Maximum area is 200,000 km² for performance reasons.',
    target: '[data-tutorial="map-container"]',
    position: 'center',
    actionType: 'draw',
    waitForAction: true,
  },
  {
    id: 28,
    phase: 'Statistical Analysis',
    title: 'Calculate Statistics',
    content: 'Click "Calculate Stats" to generate a breakdown of land cover types in your drawn area.',
    target: '[data-tutorial="stats-calculate"]',
    position: 'top',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 29,
    phase: 'Statistical Analysis',
    title: 'View Results',
    content: 'The chart shows the percentage of each land cover type in your area. Use this for analysis and reporting.',
    target: '[data-tutorial="stats-chart"]',
    position: 'left',
    actionType: 'none',
    waitForAction: false,
  },

  // ─── Phase 6: AI Assistant (Steps 30–31) ────────────────────────
  {
    id: 30,
    phase: 'AI Assistant',
    title: 'Open AI Copilot',
    content: 'Click the AI button to get help with the map, data, or any questions you have.',
    target: '[data-tutorial="ai-button"]',
    position: 'left',
    actionType: 'click',
    waitForAction: true,
  },
  {
    id: 31,
    phase: 'AI Assistant',
    title: 'Chat with AI',
    content: 'Type your question in the chat and press Enter. The AI will help you analyze data or understand features. The tutorial advances after your message is sent.',
    target: '[data-tutorial="ai-chat-input"]',
    position: 'left',
    actionType: 'type',
    waitForAction: true,
  },

  // ─── Final Step ─────────────────────────────────────────────────
  {
    id: 32,
    phase: 'Complete',
    title: 'Tutorial Complete!',
    content: 'You\'ve learned all the key features! Click "End Tour" to mark it as complete. You can always restart it from the "Show Tutorial" button in the sidebar.',
    target: 'body',
    position: 'center',
    actionType: 'none',
    waitForAction: false,
  },
]
